"""Container environment lifecycle manager for Sentinel.

Manages Docker Compose environments per ticket: auto-detects project type
from repository contents (.lando.yml), translates to Compose, and handles
the full lifecycle (setup → exec → teardown).

Designed with a runtime-agnostic interface to support DooD (Phase 1) and
Sysbox (Phase 2) without changes to the execute flow.
"""

import logging
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Optional

import yaml

from src.compose_runner import ComposeRunner, ComposeResult
from src.config_loader import get_config
from src.lando_translator import LandoTranslator
from src.utils.perf import timed

logger = logging.getLogger(__name__)

# Compose file name generated by Sentinel
SENTINEL_COMPOSE_FILE = "docker-compose.sentinel.yml"


@dataclass
class EnvironmentInfo:
    """Information about a running container environment."""

    active: bool
    ticket_id: str
    project_name: str = ""
    compose_file: Optional[Path] = None
    services: list[str] = field(default_factory=list)
    tooling: dict[str, str] = field(default_factory=dict)


class EnvironmentManager:
    """Manages container environments for Sentinel ticket workspaces.

    Auto-detects project type from repository contents and sets up
    the appropriate container environment. Currently supports:
    - Lando projects (.lando.yml) → Docker Compose translation
    - No environment (Python, etc.) → no-op

    The interface is runtime-agnostic: DooD and Sysbox both use the
    same setup/teardown/exec methods.
    """

    def __init__(self) -> None:
        """Initialize environment manager."""
        self.config = get_config()
        self._environments: dict[str, EnvironmentInfo] = {}
        self._runners: dict[str, ComposeRunner] = {}

    def get_environment_config(self) -> dict[str, Any]:
        """Get environment configuration with defaults.

        Returns:
            Environment config dictionary
        """
        defaults = {
            "runtime": "dood",
            "health_timeout": 120,
            "auto_detect": True,
            "auto_cleanup": True,
            "volume_name": "sentinel-projects",
        }
        env_config = self.config.get("environment", {})
        if isinstance(env_config, dict):
            defaults.update(env_config)
        return defaults

    def detect_project_type(self, worktree_path: Path) -> Optional[str]:
        """Detect the project type from repository contents.

        Args:
            worktree_path: Path to the project worktree

        Returns:
            Project type string ("lando", or None for no container needed)
        """
        if (worktree_path / ".lando.yml").exists():
            return "lando"
        if (worktree_path / ".lando.local.yml").exists():
            return "lando"
        return None

    def setup(self, worktree_path: Path, ticket_id: str) -> EnvironmentInfo:
        """Set up the container environment for a ticket.

        Auto-detects project type and starts appropriate services.
        If no container environment is needed, returns inactive EnvironmentInfo.

        Args:
            worktree_path: Path to the project worktree
            ticket_id: Ticket ID for unique naming

        Returns:
            EnvironmentInfo with setup details

        Raises:
            RuntimeError: If environment setup fails
        """
        with timed("env.setup", meta={"ticket": ticket_id}):
            return self._setup_inner(worktree_path, ticket_id)

    def _setup_inner(self, worktree_path: Path, ticket_id: str) -> EnvironmentInfo:
        env_config = self.get_environment_config()

        if not env_config.get("auto_detect", True):
            logger.info("Environment auto-detection disabled")
            info = EnvironmentInfo(active=False, ticket_id=ticket_id)
            self._environments[ticket_id] = info
            return info

        project_type = self.detect_project_type(worktree_path)

        if project_type is None:
            logger.info(f"No container environment needed for {ticket_id}")
            info = EnvironmentInfo(active=False, ticket_id=ticket_id)
            self._environments[ticket_id] = info
            return info

        if project_type == "lando":
            return self._setup_lando(worktree_path, ticket_id, env_config)

        logger.warning(f"Unknown project type '{project_type}' for {ticket_id}")
        info = EnvironmentInfo(active=False, ticket_id=ticket_id)
        self._environments[ticket_id] = info
        return info

    def teardown(self, ticket_id: str) -> bool:
        """Tear down the container environment for a ticket.

        Safe to call even if no environment is active (no-op).

        Args:
            ticket_id: Ticket ID

        Returns:
            True if teardown succeeded (or nothing to tear down)
        """
        env_info = self._environments.get(ticket_id)
        if not env_info or not env_info.active:
            return True

        runner = self._runners.get(ticket_id)
        if not runner:
            logger.warning(f"No compose runner found for {ticket_id}")
            return True

        logger.info(f"Tearing down environment for {ticket_id}")

        # Stop and remove containers + volumes
        result = runner.down(volumes=True)

        # Remove the per-ticket projects volume. Compose's --volumes only
        # cleans up compose-managed volumes; ours is declared external,
        # so we remove it explicitly. Best-effort — _remove_volume logs
        # rather than raises if the volume is in use or already gone.
        self._remove_volume(self._volume_name_for(ticket_id))

        if not result.success:
            logger.error(f"Teardown failed for {ticket_id}: {result.stderr}")
            # Try to clean up orphans as fallback
            runner.cleanup_orphans()
            return False

        # Update state
        env_info.active = False
        del self._runners[ticket_id]

        logger.info(f"Environment torn down for {ticket_id}")
        return True

    def exec(
        self,
        ticket_id: str,
        service: str,
        command: str | list[str],
        user: Optional[str] = None,
        workdir: Optional[str] = None,
    ) -> ComposeResult:
        """Execute a command in a running service container.

        Args:
            ticket_id: Ticket ID
            service: Service name (e.g., "appserver", "database")
            command: Command to execute
            user: Run as specific user
            workdir: Working directory inside container

        Returns:
            ComposeResult with command output

        Raises:
            RuntimeError: If no environment is active for this ticket
        """
        runner = self._runners.get(ticket_id)
        if not runner:
            raise RuntimeError(f"No active environment for {ticket_id}")

        return runner.exec(service, command, user=user, workdir=workdir)

    def is_running(self, ticket_id: str) -> bool:
        """Check if an environment is running for a ticket.

        Args:
            ticket_id: Ticket ID

        Returns:
            True if services are running
        """
        env_info = self._environments.get(ticket_id)
        if not env_info or not env_info.active:
            return False

        runner = self._runners.get(ticket_id)
        if not runner:
            return False

        services = runner.ps()
        return any(svc.state == "running" for svc in services)

    def get_exec_callback(self, ticket_id: str, service: str = "appserver") -> Callable:
        """Get a callback function for executing commands in a service.

        Useful for passing to agents as their command executor.

        Args:
            ticket_id: Ticket ID
            service: Default service to exec in

        Returns:
            Callable that takes a command string and returns (stdout, stderr, returncode)
        """
        def exec_fn(command: str) -> tuple[str, str, int]:
            result = self.exec(ticket_id, service, command)
            return result.stdout, result.stderr, result.returncode

        return exec_fn

    def get_environment_info(self, ticket_id: str) -> Optional[EnvironmentInfo]:
        """Get environment info for a ticket.

        Args:
            ticket_id: Ticket ID

        Returns:
            EnvironmentInfo or None
        """
        return self._environments.get(ticket_id)

    @staticmethod
    def _volume_name_for(ticket_id: str) -> str:
        """Construct a per-ticket project volume name.

        Each ticket gets its own ``sentinel-projects-<slug>`` volume,
        seeded fresh from the worktree on every setup. This replaces the
        previous shared ``sentinel-projects`` volume, which silently
        drifted: populated once, never refreshed, so ``composer install``
        in the appserver kept reading a stale ``composer.lock`` regardless
        of what the worktree on disk actually contained.

        Slug rules: lowercased; characters outside ``[a-z0-9_-]`` collapsed
        to ``-``. Docker volume names accept ``[a-zA-Z0-9][a-zA-Z0-9_.-]*``,
        so this is a strict subset.
        """
        slug = re.sub(r"[^a-z0-9_-]", "-", ticket_id.lower())
        return f"sentinel-projects-{slug}"

    def _ensure_volume_exists(self, volume_name: str) -> None:
        """Ensure a Docker named volume exists, creating it if needed."""
        result = subprocess.run(
            ["docker", "volume", "inspect", volume_name],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            logger.info(f"Creating Docker volume '{volume_name}'")
            create_result = subprocess.run(
                ["docker", "volume", "create", volume_name],
                capture_output=True,
                text=True,
            )
            if create_result.returncode != 0:
                raise RuntimeError(
                    f"Failed to create volume '{volume_name}': {create_result.stderr}"
                )

    def _seed_volume(self, worktree_path: Path, volume_name: str) -> None:
        with timed("env.seed_volume", meta={"volume": volume_name}):
            return self._seed_volume_inner(worktree_path, volume_name)

    def _seed_volume_inner(self, worktree_path: Path, volume_name: str) -> None:
        """Wipe and re-seed the per-ticket project volume from the worktree.

        Worktrees live in sentinel-dev's container filesystem and are not
        directly visible to the host docker daemon (we run via DooD). We
        bridge that gap by tarring the worktree from sentinel-dev's local
        FS and piping the stream into a helper container that has the
        volume mounted — the tar extraction lands in the volume, which the
        appserver subsequently sees as ``/app``.

        The volume is wiped before extraction so that its contents reflect
        the current worktree exactly, never a merge of past state and
        current. This is the property that prevents lockfile drift: every
        ``composer install`` reads the lockfile that's actually on the
        branch right now.
        """
        self._ensure_volume_exists(volume_name)

        logger.info(
            f"Seeding volume '{volume_name}' from {worktree_path} "
            "(wipe + recopy)"
        )

        tar_proc = subprocess.Popen(
            ["tar", "-cf", "-", "-C", str(worktree_path), "."],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        docker_proc = subprocess.Popen(
            [
                "docker", "run", "--rm", "-i",
                "-v", f"{volume_name}:/dst",
                "alpine",
                "sh", "-c",
                # Wipe both regular and dotfile entries; suppress "no match"
                # noise from the second glob if the volume was empty.
                "rm -rf /dst/* /dst/.[!.]* 2>/dev/null; tar -xf - -C /dst",
            ],
            stdin=tar_proc.stdout,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
        )
        # Allow tar to receive SIGPIPE if docker exits early.
        if tar_proc.stdout is not None:
            tar_proc.stdout.close()

        docker_out, docker_err = docker_proc.communicate()
        tar_proc.wait()
        tar_err = b""
        if tar_proc.stderr is not None:
            tar_err = tar_proc.stderr.read()
            tar_proc.stderr.close()

        if docker_proc.returncode != 0 or tar_proc.returncode != 0:
            raise RuntimeError(
                f"Failed to seed volume '{volume_name}': "
                f"tar rc={tar_proc.returncode}, "
                f"docker rc={docker_proc.returncode}; "
                f"tar stderr={tar_err.decode('utf-8', errors='replace').strip()}; "
                f"docker stderr={docker_err.decode('utf-8', errors='replace').strip()}"
            )

        logger.info(f"Volume '{volume_name}' seeded successfully")

    def _remove_volume(self, volume_name: str) -> None:
        """Best-effort removal of a per-ticket volume after teardown.

        Compose's ``down --volumes`` only cleans up compose-managed
        volumes; the project volume is declared ``external: true``, so we
        remove it explicitly. If removal fails (volume still attached, or
        already gone), we log and continue — failing teardown over a
        stranded volume isn't worth it.
        """
        result = subprocess.run(
            ["docker", "volume", "rm", volume_name],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            logger.warning(
                f"Could not remove volume '{volume_name}': {result.stderr.strip()}"
            )

    def _setup_lando(
        self,
        worktree_path: Path,
        ticket_id: str,
        env_config: dict[str, Any],
    ) -> EnvironmentInfo:
        """Set up environment from .lando.yml.

        Args:
            worktree_path: Path to project worktree
            ticket_id: Ticket ID
            env_config: Environment configuration

        Returns:
            EnvironmentInfo with active environment details

        Raises:
            RuntimeError: If setup fails
        """
        # Per-ticket volume name. The legacy "sentinel-projects" key in
        # env_config is ignored — it pointed at a shared volume that
        # silently drifted across runs. We construct a fresh per-ticket
        # name and seed it from the worktree below.
        volume_name = self._volume_name_for(ticket_id)
        health_timeout = env_config.get("health_timeout", 120)

        # Find Lando config
        lando_path = worktree_path / ".lando.yml"
        if not lando_path.exists():
            lando_path = worktree_path / ".lando.local.yml"

        logger.info(f"Translating {lando_path} for {ticket_id}")

        # Translate .lando.yml → docker-compose.sentinel.yml
        translator = LandoTranslator.from_file(lando_path)
        compose_dict = translator.translate(ticket_id, volume_name=volume_name)

        # Write compose file
        compose_file = worktree_path / SENTINEL_COMPOSE_FILE
        with open(compose_file, "w") as f:
            yaml.dump(compose_dict, f, default_flow_style=False, sort_keys=False)

        logger.info(f"Generated {compose_file}")

        # Seed the per-ticket volume from the worktree BEFORE bringing
        # services up. The appserver mounts this volume as /app, so
        # anything not in the volume at this point is invisible to
        # composer/drush/phpunit. Wipe-and-recopy guarantees /app reflects
        # the worktree exactly — no inheritance from prior runs.
        self._seed_volume(worktree_path, volume_name)

        # Create compose runner
        project_name = f"sentinel-{ticket_id}".lower()
        runner = ComposeRunner(compose_file=compose_file, project_name=project_name)

        # Start services
        logger.info(f"Starting services for {ticket_id}")
        result = runner.up()
        if not result.success:
            # Remove the seeded volume so a retry starts clean (otherwise
            # it leaks until the next teardown of this ticket).
            self._remove_volume(volume_name)
            raise RuntimeError(
                f"Failed to start services for {ticket_id}: {result.stderr}"
            )

        # Wait for health
        if not runner.wait_for_healthy(timeout=health_timeout):
            # Log service status for debugging
            services = runner.ps()
            for svc in services:
                if svc.state != "running" or (svc.health and svc.health != "healthy"):
                    logs = runner.logs(service=svc.name, tail=20)
                    logger.error(f"Service {svc.name} ({svc.state}/{svc.health}): {logs.stdout}")

            # Clean up on failure — compose down + remove per-ticket volume
            # so a retry starts from a clean slate (no half-populated /app).
            runner.down(volumes=True)
            self._remove_volume(volume_name)
            raise RuntimeError(
                f"Services failed to become healthy for {ticket_id} "
                f"(timeout: {health_timeout}s)"
            )

        # Run post-start commands (from Lando build_as_root, build, run_as_root)
        self._run_post_start_commands(runner, compose_dict)

        # Extract service info
        service_names = list(compose_dict.get("services", {}).keys())
        tooling = translator.get_tooling_commands()

        # Store state
        info = EnvironmentInfo(
            active=True,
            ticket_id=ticket_id,
            project_name=project_name,
            compose_file=compose_file,
            services=service_names,
            tooling=tooling,
        )
        self._environments[ticket_id] = info
        self._runners[ticket_id] = runner

        logger.info(
            f"Environment ready for {ticket_id}: "
            f"services={service_names}, tooling={list(tooling.keys())}"
        )
        return info

    def _run_post_start_commands(
        self,
        runner: ComposeRunner,
        compose_dict: dict[str, Any],
    ) -> None:
        """Execute post-start commands stored in service labels.

        These come from Lando's build_as_root, build, and run_as_root keys.

        Args:
            runner: ComposeRunner instance
            compose_dict: Parsed compose configuration
        """
        with timed("env.post_start_commands"):
            for svc_name, svc_config in compose_dict.get("services", {}).items():
                labels = svc_config.get("labels", {})
                commands_str = labels.get("sentinel.post_start_commands", "")

                if not commands_str:
                    continue

                commands = commands_str.split(";")
                for cmd in commands:
                    cmd = cmd.strip()
                    if not cmd:
                        continue

                    # Tag the kind so the autopsy can group composer / drush /
                    # other build commands separately even when invoked here.
                    cmd_lower = cmd.lower()
                    if "composer" in cmd_lower:
                        kind = "composer"
                    elif "drush" in cmd_lower:
                        kind = "drush"
                    elif "git " in cmd_lower or cmd_lower.startswith("git"):
                        kind = "git"
                    else:
                        kind = "other"
                    with timed(
                        f"env.post_start.{kind}",
                        meta={"service": svc_name, "cmd_preview": cmd[:80]},
                    ):
                        logger.info(f"Running post-start command in {svc_name}: {cmd}")
                        result = runner.exec(svc_name, cmd, user="root")
                        if not result.success:
                            logger.warning(
                                f"Post-start command failed in {svc_name}: "
                                f"{cmd}\n{result.stderr}"
                            )


def remove_ticket_volumes(ticket_id: str, compose_project: str) -> list[str]:
    """Idempotently remove the per-ticket Docker volumes for ``ticket_id``.

    Two volumes belong to a ticket:

    * ``sentinel-projects-<slug>`` — the per-ticket *external* project
      volume seeded from the worktree. Compose's ``down --volumes``
      ignores this one because it's declared ``external: true`` in the
      generated compose file (see ``src/lando_translator.py``), so it
      must be removed explicitly.
    * ``<compose_project>_db-data`` — the compose-managed DB volume.
      ``down --volumes`` *would* remove it when the compose file exists,
      but the reset path can be invoked when the compose file is gone
      (partially-failed execute, never-executed ticket). Removing it
      explicitly here covers that gap.

    Both calls are best-effort: a missing volume is the expected
    idempotent path (logged at DEBUG), an in-use volume or other failure
    is logged at WARNING and we keep going. Failing reset over a
    stranded volume isn't worth it — mirror's ``EnvironmentManager._remove_volume``.

    Args:
        ticket_id: Ticket ID. Slugified to compute the project volume
            name (``[^a-z0-9_-]`` collapsed to ``-``); same rule as
            ``EnvironmentManager._volume_name_for``.
        compose_project: The compose project name. PRECONDITION: must
            already be lowercased by the caller (the CLI does
            ``f"sentinel-{ticket_id}".lower()``); we don't re-lower
            here so there's a single source of truth.

    Returns:
        List of volume names that were actually removed. May be empty
        if both volumes were absent.
    """
    project_slug = re.sub(r"[^a-z0-9_-]", "-", ticket_id.lower())
    candidates = [
        f"sentinel-projects-{project_slug}",
        f"{compose_project}_db-data",
    ]

    removed: list[str] = []
    for name in candidates:
        result = subprocess.run(
            ["docker", "volume", "rm", name],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            removed.append(name)
            continue

        stderr = result.stderr.strip()
        if "No such volume" in stderr or "no such volume" in stderr:
            logger.debug(f"Volume '{name}' already absent: {stderr}")
        else:
            logger.warning(f"Could not remove volume '{name}': {stderr}")

    return removed
