"""Container environment lifecycle manager for Sentinel.

Manages Docker Compose environments per ticket: auto-detects project type
from repository contents (.lando.yml), translates to Compose, and handles
the full lifecycle (setup → exec → teardown).

Designed with a runtime-agnostic interface to support DooD (Phase 1) and
Sysbox (Phase 2) without changes to the execute flow.
"""

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Optional

import yaml

from src.compose_runner import ComposeRunner, ComposeResult
from src.config_loader import get_config
from src.lando_translator import LandoTranslator

logger = logging.getLogger(__name__)

# Compose file name generated by Sentinel
SENTINEL_COMPOSE_FILE = "docker-compose.sentinel.yml"


@dataclass
class EnvironmentInfo:
    """Information about a running container environment."""

    active: bool
    ticket_id: str
    project_name: str = ""
    compose_file: Optional[Path] = None
    services: list[str] = field(default_factory=list)
    tooling: dict[str, str] = field(default_factory=dict)


class EnvironmentManager:
    """Manages container environments for Sentinel ticket workspaces.

    Auto-detects project type from repository contents and sets up
    the appropriate container environment. Currently supports:
    - Lando projects (.lando.yml) → Docker Compose translation
    - No environment (Python, etc.) → no-op

    The interface is runtime-agnostic: DooD and Sysbox both use the
    same setup/teardown/exec methods.
    """

    def __init__(self) -> None:
        """Initialize environment manager."""
        self.config = get_config()
        self._environments: dict[str, EnvironmentInfo] = {}
        self._runners: dict[str, ComposeRunner] = {}

    def get_environment_config(self) -> dict[str, Any]:
        """Get environment configuration with defaults.

        Returns:
            Environment config dictionary
        """
        defaults = {
            "runtime": "dood",
            "health_timeout": 120,
            "auto_detect": True,
            "auto_cleanup": True,
            "volume_name": "sentinel-projects",
        }
        env_config = self.config.get("environment", {})
        if isinstance(env_config, dict):
            defaults.update(env_config)
        return defaults

    def detect_project_type(self, worktree_path: Path) -> Optional[str]:
        """Detect the project type from repository contents.

        Args:
            worktree_path: Path to the project worktree

        Returns:
            Project type string ("lando", or None for no container needed)
        """
        if (worktree_path / ".lando.yml").exists():
            return "lando"
        if (worktree_path / ".lando.local.yml").exists():
            return "lando"
        return None

    def setup(self, worktree_path: Path, ticket_id: str) -> EnvironmentInfo:
        """Set up the container environment for a ticket.

        Auto-detects project type and starts appropriate services.
        If no container environment is needed, returns inactive EnvironmentInfo.

        Args:
            worktree_path: Path to the project worktree
            ticket_id: Ticket ID for unique naming

        Returns:
            EnvironmentInfo with setup details

        Raises:
            RuntimeError: If environment setup fails
        """
        env_config = self.get_environment_config()

        if not env_config.get("auto_detect", True):
            logger.info("Environment auto-detection disabled")
            info = EnvironmentInfo(active=False, ticket_id=ticket_id)
            self._environments[ticket_id] = info
            return info

        project_type = self.detect_project_type(worktree_path)

        if project_type is None:
            logger.info(f"No container environment needed for {ticket_id}")
            info = EnvironmentInfo(active=False, ticket_id=ticket_id)
            self._environments[ticket_id] = info
            return info

        if project_type == "lando":
            return self._setup_lando(worktree_path, ticket_id, env_config)

        logger.warning(f"Unknown project type '{project_type}' for {ticket_id}")
        info = EnvironmentInfo(active=False, ticket_id=ticket_id)
        self._environments[ticket_id] = info
        return info

    def teardown(self, ticket_id: str) -> bool:
        """Tear down the container environment for a ticket.

        Safe to call even if no environment is active (no-op).

        Args:
            ticket_id: Ticket ID

        Returns:
            True if teardown succeeded (or nothing to tear down)
        """
        env_info = self._environments.get(ticket_id)
        if not env_info or not env_info.active:
            return True

        runner = self._runners.get(ticket_id)
        if not runner:
            logger.warning(f"No compose runner found for {ticket_id}")
            return True

        logger.info(f"Tearing down environment for {ticket_id}")

        # Stop and remove containers + volumes
        result = runner.down(volumes=True)
        if not result.success:
            logger.error(f"Teardown failed for {ticket_id}: {result.stderr}")
            # Try to clean up orphans as fallback
            runner.cleanup_orphans()
            return False

        # Update state
        env_info.active = False
        del self._runners[ticket_id]

        logger.info(f"Environment torn down for {ticket_id}")
        return True

    def exec(
        self,
        ticket_id: str,
        service: str,
        command: str | list[str],
        user: Optional[str] = None,
        workdir: Optional[str] = None,
    ) -> ComposeResult:
        """Execute a command in a running service container.

        Args:
            ticket_id: Ticket ID
            service: Service name (e.g., "appserver", "database")
            command: Command to execute
            user: Run as specific user
            workdir: Working directory inside container

        Returns:
            ComposeResult with command output

        Raises:
            RuntimeError: If no environment is active for this ticket
        """
        runner = self._runners.get(ticket_id)
        if not runner:
            raise RuntimeError(f"No active environment for {ticket_id}")

        return runner.exec(service, command, user=user, workdir=workdir)

    def is_running(self, ticket_id: str) -> bool:
        """Check if an environment is running for a ticket.

        Args:
            ticket_id: Ticket ID

        Returns:
            True if services are running
        """
        env_info = self._environments.get(ticket_id)
        if not env_info or not env_info.active:
            return False

        runner = self._runners.get(ticket_id)
        if not runner:
            return False

        services = runner.ps()
        return any(svc.state == "running" for svc in services)

    def get_exec_callback(self, ticket_id: str, service: str = "appserver") -> Callable:
        """Get a callback function for executing commands in a service.

        Useful for passing to agents as their command executor.

        Args:
            ticket_id: Ticket ID
            service: Default service to exec in

        Returns:
            Callable that takes a command string and returns (stdout, stderr, returncode)
        """
        def exec_fn(command: str) -> tuple[str, str, int]:
            result = self.exec(ticket_id, service, command)
            return result.stdout, result.stderr, result.returncode

        return exec_fn

    def get_environment_info(self, ticket_id: str) -> Optional[EnvironmentInfo]:
        """Get environment info for a ticket.

        Args:
            ticket_id: Ticket ID

        Returns:
            EnvironmentInfo or None
        """
        return self._environments.get(ticket_id)

    def _ensure_volume_exists(self, volume_name: str) -> None:
        """Ensure a Docker named volume exists, creating it if needed."""
        import subprocess

        result = subprocess.run(
            ["docker", "volume", "inspect", volume_name],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            logger.info(f"Creating Docker volume '{volume_name}'")
            create_result = subprocess.run(
                ["docker", "volume", "create", volume_name],
                capture_output=True,
                text=True,
            )
            if create_result.returncode != 0:
                raise RuntimeError(
                    f"Failed to create volume '{volume_name}': {create_result.stderr}"
                )

    def _setup_lando(
        self,
        worktree_path: Path,
        ticket_id: str,
        env_config: dict[str, Any],
    ) -> EnvironmentInfo:
        """Set up environment from .lando.yml.

        Args:
            worktree_path: Path to project worktree
            ticket_id: Ticket ID
            env_config: Environment configuration

        Returns:
            EnvironmentInfo with active environment details

        Raises:
            RuntimeError: If setup fails
        """
        volume_name = env_config.get("volume_name", "sentinel-projects")
        health_timeout = env_config.get("health_timeout", 120)

        # Find Lando config
        lando_path = worktree_path / ".lando.yml"
        if not lando_path.exists():
            lando_path = worktree_path / ".lando.local.yml"

        logger.info(f"Translating {lando_path} for {ticket_id}")

        # Translate .lando.yml → docker-compose.sentinel.yml
        translator = LandoTranslator.from_file(lando_path)
        compose_dict = translator.translate(ticket_id, volume_name=volume_name)

        # Write compose file
        compose_file = worktree_path / SENTINEL_COMPOSE_FILE
        with open(compose_file, "w") as f:
            yaml.dump(compose_dict, f, default_flow_style=False, sort_keys=False)

        logger.info(f"Generated {compose_file}")

        # Ensure the shared volume exists before starting services
        self._ensure_volume_exists(volume_name)

        # Create compose runner
        project_name = f"sentinel-{ticket_id}".lower()
        runner = ComposeRunner(compose_file=compose_file, project_name=project_name)

        # Start services
        logger.info(f"Starting services for {ticket_id}")
        result = runner.up()
        if not result.success:
            raise RuntimeError(
                f"Failed to start services for {ticket_id}: {result.stderr}"
            )

        # Wait for health
        if not runner.wait_for_healthy(timeout=health_timeout):
            # Log service status for debugging
            services = runner.ps()
            for svc in services:
                if svc.state != "running" or (svc.health and svc.health != "healthy"):
                    logs = runner.logs(service=svc.name, tail=20)
                    logger.error(f"Service {svc.name} ({svc.state}/{svc.health}): {logs.stdout}")

            # Clean up on failure
            runner.down(volumes=True)
            raise RuntimeError(
                f"Services failed to become healthy for {ticket_id} "
                f"(timeout: {health_timeout}s)"
            )

        # Run post-start commands (from Lando build_as_root, build, run_as_root)
        self._run_post_start_commands(runner, compose_dict)

        # Extract service info
        service_names = list(compose_dict.get("services", {}).keys())
        tooling = translator.get_tooling_commands()

        # Store state
        info = EnvironmentInfo(
            active=True,
            ticket_id=ticket_id,
            project_name=project_name,
            compose_file=compose_file,
            services=service_names,
            tooling=tooling,
        )
        self._environments[ticket_id] = info
        self._runners[ticket_id] = runner

        logger.info(
            f"Environment ready for {ticket_id}: "
            f"services={service_names}, tooling={list(tooling.keys())}"
        )
        return info

    def _run_post_start_commands(
        self,
        runner: ComposeRunner,
        compose_dict: dict[str, Any],
    ) -> None:
        """Execute post-start commands stored in service labels.

        These come from Lando's build_as_root, build, and run_as_root keys.

        Args:
            runner: ComposeRunner instance
            compose_dict: Parsed compose configuration
        """
        for svc_name, svc_config in compose_dict.get("services", {}).items():
            labels = svc_config.get("labels", {})
            commands_str = labels.get("sentinel.post_start_commands", "")

            if not commands_str:
                continue

            commands = commands_str.split(";")
            for cmd in commands:
                cmd = cmd.strip()
                if not cmd:
                    continue

                logger.info(f"Running post-start command in {svc_name}: {cmd}")
                result = runner.exec(svc_name, cmd, user="root")
                if not result.success:
                    logger.warning(
                        f"Post-start command failed in {svc_name}: "
                        f"{cmd}\n{result.stderr}"
                    )
